version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Running build...
      - python application.py
artifacts:
  files:
    - '**/*'
